[tool.poetry]
name = "mass"
version = "0.1.0"
description = ""
authors = ["Marcos Romero Martín"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.0"
behave = "^1.2.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
setup = "poetry install"
check = "python -m compileall mass/"